# Generated by Django 4.2.5 on 2024-02-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='downloaded_files/', verbose_name='Загружаемый файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время загрузки файла')),
                ('processed', models.BooleanField(default=False, verbose_name='Статус обработки файла')),
            ],
        ),
    ]
