# Generated by Django 4.2.5 on 2024-02-17 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ('uploaded_at',)},
        ),
    ]
