# Generated by Django 4.2.5 on 2024-02-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_file_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ('uploaded_at',), 'verbose_name': 'Загруженные файлы', 'verbose_name_plural': 'Загруженные файлы'},
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки файла'),
        ),
    ]
